"""empty message

Revision ID: 8d134a24080e
Revises: 5cae9c7e95e8
Create Date: 2020-10-29 11:22:04.799934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d134a24080e'
down_revision = '5cae9c7e95e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artists_facebook_link_key', 'artists', type_='unique')
    op.drop_constraint('artists_website_key', 'artists', type_='unique')
    op.drop_constraint('venues_facebook_link_key', 'venues', type_='unique')
    op.drop_constraint('venues_website_key', 'venues', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('venues_website_key', 'venues', ['website'])
    op.create_unique_constraint('venues_facebook_link_key', 'venues', ['facebook_link'])
    op.create_unique_constraint('artists_website_key', 'artists', ['website'])
    op.create_unique_constraint('artists_facebook_link_key', 'artists', ['facebook_link'])
    # ### end Alembic commands ###
